CREATE TABLE BLOCK (
	BLOCK_NUMBER INTEGER NOT NULL,
	BLOCK_VERSION SMALLINT NOT NULL,
	BLOCK_MERKLE_ROOT VARCHAR(100) NOT NULL,
	BLOCK_TIME VARCHAR(100) NOT NULL,
	BLOCK_NUMBER_OF_TRANSACTIONS INTEGER NOT NULL
	);
                            
CREATE TABLE TRANSACTION (
	BLOCK_NUMBER_FK INTEGER NOT NULL,
	TRANSACTION_INDEX INTEGER NOT NULL, 
	TRANSACTION_ID VARCHAR(100) NOT NULL, 
	TRANSACTION_NUMBER_OF_INPUTS SMALLINT NOT NULL,
	TRANSACTION_NUMBER_OF_OUTPUTS SMALLINT NOT NULL
	);

CREATE TABLE TRANSACTION_INPUT (
	BLOCK_NUMBER_FK INTEGER NOT NULL,
	TRANSACTION_INDEX_FK INTEGER NOT NULL, 
	TRANSACTION_ID_FK VARCHAR(100) NOT NULL, 
	TRANSACTION_INPUT_INDEX INTEGER NOT NULL, 
	PARENT_TRANSACTION_ID_FK VARCHAR(100) NOT NULL,
	INDEX_INTO_PARENT_TRANSACTION INTEGER NOT NULL
	);

CREATE TABLE TRANSACTION_OUTPUT (
	BLOCK_NUMBER_FK INTEGER NOT NULL,
	TRANSACTION_INDEX_FK INTEGER NOT NULL, 
	TRANSACTION_ID_FK VARCHAR(100) NOT NULL, 
	TRANSACTION_OUTPUT_INDEX INTEGER NOT NULL, 
	ADDRESS VARCHAR(100) NOT NULL,
	AMOUNT DOUBLE NOT NULL
	);
